services:
  nginx:
    container_name: nginx-container
    image: nginx:1.29-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/fastapi-1.lucian.studio/fullchain.pem:/etc/letsencrypt/live/fastapi-1.lucian.studio/fullchain.pem:ro
      - /etc/letsencrypt/live/fastapi-1.lucian.studio/privkey.pem:/etc/letsencrypt/live/fastapi-1.lucian.studio/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fastapi.conf:/etc/nginx/conf.d/fastapi.conf:ro
    networks:
      - my-network
  wapang:
    container_name: fastapi-container
    image: odumag99/fastapi-seminar-demo:latest
    networks:
      - my-network
networks:
  my-network: